Flappy Dino com geração procedural
ViniciusBPessoa/IA_project_clasic_games pull request #6
Opened 2023-08-18 03:44 UTC by IrlanAndrade

Implementado atualmente geração procedural das formas.

2023-08-18 03:51 UTC, ViniciusBPessoa requested changes
algumas alterações foram solicitadas

2023-08-18 03:51 UTC, ViniciusBPessoa commented on IA_classic_games/Assets/FLAPPY_DINO/Scripts/Dino/Morte.cs
remover código desnecessário

2023-08-18 03:51 UTC, ViniciusBPessoa commented on IA_classic_games/Assets/FLAPPY_DINO/Scripts/Forma/Gerencia_Forma.cs
Código desnecessário mais uma vez nas linhas

11 - 14

2023-08-22 23:46 UTC, IrlanAndrade reviewed
Reavaliado

2023-08-22 23:46 UTC, IrlanAndrade commented on IA_classic_games/Assets/FLAPPY_DINO/Scripts/Forma/Gerencia_Forma.cs
Arrumado

2023-08-23 00:37 UTC, ViniciusBPessoa approved these changes
Aiiiii o cara manja

2023-08-23 00:37 UTC, ViniciusBPessoa commented
Isso não é um botão

2023-08-23 00:37 UTC, merged